# ruff: noqa

#
# Export
#
# https://docs.senzing.com/python/3/g2engine/reporting/index.html#exportjsonentityreport
EXPORT_MATCHED_LIMIT10 = \
[{'RELATED_ENTITIES': [{'ENTITY_ID': 32,
                        'ENTITY_NAME': 'Eddie Knight',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 41,
                        'ENTITY_NAME': 'Mark Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+PNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 42,
                        'ENTITY_NAME': 'Marsha Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 1,
                      'ENTITY_NAME': 'Marie Kusha',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1016'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1017'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1018'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1015'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 38,
                        'ENTITY_NAME': 'Robert E Smith Sr',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200001,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 2,
                      'ENTITY_NAME': 'Robert Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1004'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1003'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1001'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1002'}]}},
 {'RELATED_ENTITIES': [],
  'RESOLVED_ENTITY': {'ENTITY_ID': 3,
                      'ENTITY_NAME': 'Muhammed Antoun',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1022'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1023'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 1,
                        'ENTITY_NAME': 'Marie Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 41,
                        'ENTITY_NAME': 'Mark Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 42,
                        'ENTITY_NAME': 'Marsha Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 32,
                      'ENTITY_NAME': 'Eddie Knight',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1010'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1011'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1009'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1014'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1012'}]}},
 {'RELATED_ENTITIES': [],
  'RESOLVED_ENTITY': {'ENTITY_ID': 33,
                      'ENTITY_NAME': 'Louis Garsky',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1030'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1031'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 2,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200001,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 38,
                      'ENTITY_NAME': 'Robert E Smith Sr',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1005'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1006'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 1,
                        'ENTITY_NAME': 'Marie Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 32,
                        'ENTITY_NAME': 'Eddie Knight',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 41,
                        'ENTITY_NAME': 'Mark Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 42,
                      'ENTITY_NAME': 'Marsha Kusha',
                      'RECORDS': [{'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1021'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1020'}]}},
 {'RELATED_ENTITIES': [],
  'RESOLVED_ENTITY': {'ENTITY_ID': 45,
                      'ENTITY_NAME': 'Daniella Shaw',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1032'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1033'}]}},
 {'RELATED_ENTITIES': [],
  'RESOLVED_ENTITY': {'ENTITY_ID': 54,
                      'ENTITY_NAME': 'Maria Luis Medina Sentosa',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1035'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1034'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1036'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1038'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB-PASSPORT',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 66,
                      'ENTITY_NAME': 'Patrick Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1045'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1043'}]}}]

EXPORT_POSSIBLE_MATCHES_LIMIT10 = \
[{'RELATED_ENTITIES': [{'ENTITY_ID': 38,
                        'ENTITY_NAME': 'Robert E Smith Sr',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200001,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 2,
                      'ENTITY_NAME': 'Robert Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1004'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1003'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1001'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1002'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 200022,
                        'ENTITY_NAME': 'David Dobbins Senior',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-GENERATION',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 31,
                      'ENTITY_NAME': 'David Dobbins Jr',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1028'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 2,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200001,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 38,
                      'ENTITY_NAME': 'Robert E Smith Sr',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1005'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1006'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF',
                        'IS_AMBIGUOUS': 1,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS (Ambiguous)',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 66,
                        'ENTITY_NAME': 'Patrick Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 57,
                      'ENTITY_NAME': 'John Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1039'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF',
                        'IS_AMBIGUOUS': 1,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS (Ambiguous)',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 66,
                        'ENTITY_NAME': 'Patrick Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 63,
                      'ENTITY_NAME': 'John Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1040'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB-PASSPORT',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 66,
                      'ENTITY_NAME': 'Patrick Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1045'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1043'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 66,
                        'ENTITY_NAME': 'Patrick Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB-PASSPORT',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 68,
                      'ENTITY_NAME': 'Patricia Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1044'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1046'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 77,
                        'ENTITY_NAME': 'Jay Jones',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 75,
                      'ENTITY_NAME': 'Jones Jay',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1058'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 75,
                        'ENTITY_NAME': 'Jones Jay',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 77,
                      'ENTITY_NAME': 'Jay Jones',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1057'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 139,
                        'ENTITY_NAME': 'Morris Klein II',
                        'ERRULE_CODE': 'CNAME_CSTAB',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+DOB-GENERATION',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 135,
                      'ENTITY_NAME': 'Morris Klein I',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1089'}]}}]

EXPORT_POSSIBLE_RELATIONSHIPS_LIMIT10 = \
[{'RELATED_ENTITIES': [{'ENTITY_ID': 32,
                        'ENTITY_NAME': 'Eddie Knight',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 41,
                        'ENTITY_NAME': 'Mark Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+PNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 42,
                        'ENTITY_NAME': 'Marsha Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 1,
                      'ENTITY_NAME': 'Marie Kusha',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1016'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1017'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1018'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1015'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 38,
                        'ENTITY_NAME': 'Robert E Smith Sr',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200001,
                        'ENTITY_NAME': 'Robert Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 2,
                      'ENTITY_NAME': 'Robert Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1004'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1003'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1001'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1002'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 1,
                        'ENTITY_NAME': 'Marie Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 41,
                        'ENTITY_NAME': 'Mark Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 42,
                        'ENTITY_NAME': 'Marsha Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 32,
                      'ENTITY_NAME': 'Eddie Knight',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1010'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1011'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1009'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1014'},
                                  {'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1012'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 1,
                        'ENTITY_NAME': 'Marie Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+PNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 32,
                        'ENTITY_NAME': 'Eddie Knight',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 42,
                        'ENTITY_NAME': 'Marsha Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 41,
                      'ENTITY_NAME': 'Mark Kusha',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1019'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 1,
                        'ENTITY_NAME': 'Marie Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 32,
                        'ENTITY_NAME': 'Eddie Knight',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 41,
                        'ENTITY_NAME': 'Mark Kusha',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 42,
                      'ENTITY_NAME': 'Marsha Kusha',
                      'RECORDS': [{'DATA_SOURCE': 'WATCHLIST',
                                   'RECORD_ID': '1021'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1020'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF',
                        'IS_AMBIGUOUS': 1,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS (Ambiguous)',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 66,
                        'ENTITY_NAME': 'Patrick Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 57,
                      'ENTITY_NAME': 'John Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1039'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CNAME_CFF',
                        'IS_AMBIGUOUS': 1,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS (Ambiguous)',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 66,
                        'ENTITY_NAME': 'Patrick Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 63,
                      'ENTITY_NAME': 'John Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1040'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 68,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB-PASSPORT',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 66,
                      'ENTITY_NAME': 'Patrick Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1045'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1043'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 66,
                        'ENTITY_NAME': 'Patrick Smith',
                        'ERRULE_CODE': 'CNAME_CFF_DEXCL',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME+ADDRESS-DOB-PASSPORT',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 200025,
                        'ENTITY_NAME': 'Patricia Smith',
                        'ERRULE_CODE': 'CNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+NAME',
                        'MATCH_LEVEL': 2,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'},
                       {'ENTITY_ID': 57,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME-DOB',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 63,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+DOB+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                       {'ENTITY_ID': 200024,
                        'ENTITY_NAME': 'John Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 68,
                      'ENTITY_NAME': 'Patricia Smith',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1044'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1046'}]}},
 {'RELATED_ENTITIES': [{'ENTITY_ID': 85,
                        'ENTITY_NAME': 'Beau Smith',
                        'ERRULE_CODE': 'CFF_SURNAME',
                        'IS_AMBIGUOUS': 0,
                        'IS_DISCLOSED': 0,
                        'MATCH_KEY': '+ADDRESS+SURNAME',
                        'MATCH_LEVEL': 3,
                        'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
  'RESOLVED_ENTITY': {'ENTITY_ID': 81,
                      'ENTITY_NAME': 'Magdalena Jones',
                      'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1054'},
                                  {'DATA_SOURCE': 'CUSTOMERS',
                                   'RECORD_ID': '1056'}]}}]

#
# Record
#
# https://docs.senzing.com/python/3/g2engine/getting/index.html#getrecord
RECORD_1001 = \
{'DATA_SOURCE': 'CUSTOMERS',
 'JSON_DATA': {'ADDR_LINE1': '123 Main Street, Las Vegas NV 89132',
               'ADDR_TYPE': 'MAILING',
               'AMOUNT': '100',
               'DATA_SOURCE': 'CUSTOMERS',
               'DATE': '1/2/18',
               'DATE_OF_BIRTH': '12/11/1978',
               'DSRC_ACTION': 'A',
               'EMAIL_ADDRESS': 'bsmith@work.com',
               'ENTITY_TYPE': 'GENERIC',
               'PHONE_NUMBER': '702-919-1300',
               'PHONE_TYPE': 'HOME',
               'PRIMARY_NAME_FIRST': 'Robert',
               'PRIMARY_NAME_LAST': 'Smith',
               'RECORD_ID': '1001',
               'RECORD_TYPE': 'PERSON',
               'STATUS': 'Active'},
 'RECORD_ID': '1001'}

#
# Entity Details
#
# https://docs.senzing.com/python/3/g2engine/getting/index.html#getentitybyentityid
ENTITY_1 = \
{'RELATED_ENTITIES': [{'ENTITY_ID': 32,
                       'ENTITY_NAME': 'Eddie Knight',
                       'ERRULE_CODE': 'CFF_SURNAME',
                       'IS_AMBIGUOUS': 0,
                       'IS_DISCLOSED': 0,
                       'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                       'MATCH_LEVEL': 3,
                       'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                      {'ENTITY_ID': 41,
                       'ENTITY_NAME': 'Mark Kusha',
                       'ERRULE_CODE': 'CFF_SURNAME',
                       'IS_AMBIGUOUS': 0,
                       'IS_DISCLOSED': 0,
                       'MATCH_KEY': '+ADDRESS+PNAME-DOB',
                       'MATCH_LEVEL': 3,
                       'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'},
                      {'ENTITY_ID': 42,
                       'ENTITY_NAME': 'Marsha Kusha',
                       'ERRULE_CODE': 'CFF_SURNAME',
                       'IS_AMBIGUOUS': 0,
                       'IS_DISCLOSED': 0,
                       'MATCH_KEY': '+ADDRESS+SURNAME-DOB-SSN',
                       'MATCH_LEVEL': 3,
                       'MATCH_LEVEL_CODE': 'POSSIBLY_RELATED'}],
 'RESOLVED_ENTITY': {'ENTITY_ID': 1,
                     'ENTITY_NAME': 'Marie Kusha',
                     'FEATURES': {'ADDRESS': [{'FEAT_DESC': '1304 Poppy Hills '
                                                            'Dr Blacklick OH '
                                                            '43004',
                                               'FEAT_DESC_VALUES': [{'FEAT_DESC': '1304 '
                                                                                  'Poppy '
                                                                                  'Hills '
                                                                                  'Dr '
                                                                                  'Blacklick '
                                                                                  'OH '
                                                                                  '43004',
                                                                     'LIB_FEAT_ID': 100099},
                                                                    {'FEAT_DESC': '1304 '
                                                                                  'Poppy '
                                                                                  'Hills '
                                                                                  'Dr '
                                                                                  '43004',
                                                                     'LIB_FEAT_ID': 100095}],
                                               'LIB_FEAT_ID': 100099,
                                               'USAGE_TYPE': 'HOME'}],
                                  'DOB': [{'FEAT_DESC': '10/28/76',
                                           'FEAT_DESC_VALUES': [{'FEAT_DESC': '10/28/76',
                                                                 'LIB_FEAT_ID': 100017},
                                                                {'FEAT_DESC': '10/27/76',
                                                                 'LIB_FEAT_ID': 100087}],
                                           'LIB_FEAT_ID': 100017}],
                                  'EMAIL': [{'FEAT_DESC': 'Kusha123@hmail.com',
                                             'FEAT_DESC_VALUES': [{'FEAT_DESC': 'Kusha123@hmail.com',
                                                                   'LIB_FEAT_ID': 100111}],
                                             'LIB_FEAT_ID': 100111}],
                                  'NAME': [{'FEAT_DESC': 'Marie Kusha',
                                            'FEAT_DESC_VALUES': [{'FEAT_DESC': 'Marie '
                                                                               'Kusha',
                                                                  'LIB_FEAT_ID': 100012},
                                                                 {'FEAT_DESC': 'Mary '
                                                                               'Kusha',
                                                                  'LIB_FEAT_ID': 100001}],
                                            'LIB_FEAT_ID': 100012,
                                            'USAGE_TYPE': 'PRIMARY'}],
                                  'PHONE': [{'FEAT_DESC': '512-353-8633',
                                             'FEAT_DESC_VALUES': [{'FEAT_DESC': '512-353-8633',
                                                                   'LIB_FEAT_ID': 100023}],
                                             'LIB_FEAT_ID': 100023,
                                             'USAGE_TYPE': 'HOME'}],
                                  'RECORD_TYPE': [{'FEAT_DESC': 'PERSON',
                                                   'FEAT_DESC_VALUES': [{'FEAT_DESC': 'PERSON',
                                                                         'LIB_FEAT_ID': 100020}],
                                                   'LIB_FEAT_ID': 100020}],
                                  'SSN': [{'FEAT_DESC': '293-90-9090',
                                           'FEAT_DESC_VALUES': [{'FEAT_DESC': '293-90-9090',
                                                                 'LIB_FEAT_ID': 100003}],
                                           'LIB_FEAT_ID': 100003}]},
                     'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                  'RECORD_ID': '1016'},
                                 {'DATA_SOURCE': 'CUSTOMERS',
                                  'RECORD_ID': '1017'},
                                 {'DATA_SOURCE': 'CUSTOMERS',
                                  'RECORD_ID': '1018'},
                                 {'DATA_SOURCE': 'CUSTOMERS',
                                  'RECORD_ID': '1015'}]}}

#
# Entity How
#
# https://docs.senzing.com/python/3/g2engine/how/index.html
ENTITY_HOW_1 = \
{'HOW_RESULTS': {'FINAL_STATE': {'NEED_REEVALUATION': 0,
                                 'VIRTUAL_ENTITIES': [{'MEMBER_RECORDS': [{'INTERNAL_ID': 1,
                                                                           'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                        'RECORD_ID': '1017'}]},
                                                                          {'INTERNAL_ID': 4,
                                                                           'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                        'RECORD_ID': '1018'}]},
                                                                          {'INTERNAL_ID': 35,
                                                                           'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                        'RECORD_ID': '1016'}]},
                                                                          {'INTERNAL_ID': 44,
                                                                           'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                        'RECORD_ID': '1015'}]}],
                                                       'VIRTUAL_ENTITY_ID': 'V1-S3'}]},
                 'RESOLUTION_STEPS': [{'INBOUND_VIRTUAL_ENTITY_ID': 'V35',
                                       'MATCH_INFO': {'ERRULE_CODE': 'CNAME_CFF_CEXCL',
                                                      'FEATURE_SCORES': {'ADDRESS': [{'CANDIDATE_FEAT': '1304 '
                                                                                                        'Poppy '
                                                                                                        'Hills '
                                                                                                        'Dr '
                                                                                                        'Blacklick '
                                                                                                        'OH '
                                                                                                        '43004',
                                                                                      'CANDIDATE_FEAT_ID': 100099,
                                                                                      'CANDIDATE_FEAT_USAGE_TYPE': 'HOME',
                                                                                      'FULL_SCORE': 100,
                                                                                      'INBOUND_FEAT': '1304 '
                                                                                                      'Poppy '
                                                                                                      'Hills '
                                                                                                      'Dr '
                                                                                                      '43004',
                                                                                      'INBOUND_FEAT_ID': 100095,
                                                                                      'INBOUND_FEAT_USAGE_TYPE': 'HOME',
                                                                                      'SCORE_BEHAVIOR': 'FF',
                                                                                      'SCORE_BUCKET': 'SAME'}],
                                                                         'DOB': [{'CANDIDATE_FEAT': '10/27/76',
                                                                                  'CANDIDATE_FEAT_ID': 100087,
                                                                                  'CANDIDATE_FEAT_USAGE_TYPE': '',
                                                                                  'FULL_SCORE': 100,
                                                                                  'INBOUND_FEAT': '10/27/76',
                                                                                  'INBOUND_FEAT_ID': 100087,
                                                                                  'INBOUND_FEAT_USAGE_TYPE': '',
                                                                                  'SCORE_BEHAVIOR': 'FMES',
                                                                                  'SCORE_BUCKET': 'SAME'}],
                                                                         'NAME': [{'CANDIDATE_FEAT': 'Mary '
                                                                                                     'Kusha',
                                                                                   'CANDIDATE_FEAT_ID': 100001,
                                                                                   'CANDIDATE_FEAT_USAGE_TYPE': 'PRIMARY',
                                                                                   'GENERATION_MATCH': -1,
                                                                                   'GNR_FN': 98,
                                                                                   'GNR_GN': 98,
                                                                                   'GNR_ON': -1,
                                                                                   'GNR_SN': 100,
                                                                                   'INBOUND_FEAT': 'Marie '
                                                                                                   'Kusha',
                                                                                   'INBOUND_FEAT_ID': 100012,
                                                                                   'INBOUND_FEAT_USAGE_TYPE': 'PRIMARY',
                                                                                   'SCORE_BEHAVIOR': 'NAME',
                                                                                   'SCORE_BUCKET': 'CLOSE'}],
                                                                         'RECORD_TYPE': [{'CANDIDATE_FEAT': 'PERSON',
                                                                                          'CANDIDATE_FEAT_ID': 100020,
                                                                                          'CANDIDATE_FEAT_USAGE_TYPE': '',
                                                                                          'FULL_SCORE': 100,
                                                                                          'INBOUND_FEAT': 'PERSON',
                                                                                          'INBOUND_FEAT_ID': 100020,
                                                                                          'INBOUND_FEAT_USAGE_TYPE': '',
                                                                                          'SCORE_BEHAVIOR': 'FVME',
                                                                                          'SCORE_BUCKET': 'SAME'}]},
                                                      'MATCH_KEY': '+NAME+DOB+ADDRESS'},
                                       'RESULT_VIRTUAL_ENTITY_ID': 'V35-S1',
                                       'STEP': 1,
                                       'VIRTUAL_ENTITY_1': {'MEMBER_RECORDS': [{'INTERNAL_ID': 35,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1016'}]}],
                                                            'VIRTUAL_ENTITY_ID': 'V35'},
                                       'VIRTUAL_ENTITY_2': {'MEMBER_RECORDS': [{'INTERNAL_ID': 44,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1015'}]}],
                                                            'VIRTUAL_ENTITY_ID': 'V44'}},
                                      {'INBOUND_VIRTUAL_ENTITY_ID': 'V1',
                                       'MATCH_INFO': {'ERRULE_CODE': 'SF1_PNAME_CSTAB',
                                                      'FEATURE_SCORES': {'NAME': [{'CANDIDATE_FEAT': 'Mary '
                                                                                                     'Kusha',
                                                                                   'CANDIDATE_FEAT_ID': 100001,
                                                                                   'CANDIDATE_FEAT_USAGE_TYPE': 'PRIMARY',
                                                                                   'GENERATION_MATCH': -1,
                                                                                   'GNR_FN': 100,
                                                                                   'GNR_GN': 100,
                                                                                   'GNR_ON': -1,
                                                                                   'GNR_SN': 100,
                                                                                   'INBOUND_FEAT': 'Mary '
                                                                                                   'Kusha',
                                                                                   'INBOUND_FEAT_ID': 100001,
                                                                                   'INBOUND_FEAT_USAGE_TYPE': 'PRIMARY',
                                                                                   'SCORE_BEHAVIOR': 'NAME',
                                                                                   'SCORE_BUCKET': 'SAME'}],
                                                                         'RECORD_TYPE': [{'CANDIDATE_FEAT': 'PERSON',
                                                                                          'CANDIDATE_FEAT_ID': 100020,
                                                                                          'CANDIDATE_FEAT_USAGE_TYPE': '',
                                                                                          'FULL_SCORE': 100,
                                                                                          'INBOUND_FEAT': 'PERSON',
                                                                                          'INBOUND_FEAT_ID': 100020,
                                                                                          'INBOUND_FEAT_USAGE_TYPE': '',
                                                                                          'SCORE_BEHAVIOR': 'FVME',
                                                                                          'SCORE_BUCKET': 'SAME'}],
                                                                         'SSN': [{'CANDIDATE_FEAT': '293-90-9090',
                                                                                  'CANDIDATE_FEAT_ID': 100003,
                                                                                  'CANDIDATE_FEAT_USAGE_TYPE': '',
                                                                                  'FULL_SCORE': 100,
                                                                                  'INBOUND_FEAT': '293-90-9090',
                                                                                  'INBOUND_FEAT_ID': 100003,
                                                                                  'INBOUND_FEAT_USAGE_TYPE': '',
                                                                                  'SCORE_BEHAVIOR': 'F1ES',
                                                                                  'SCORE_BUCKET': 'SAME'}]},
                                                      'MATCH_KEY': '+NAME+SSN'},
                                       'RESULT_VIRTUAL_ENTITY_ID': 'V1-S2',
                                       'STEP': 2,
                                       'VIRTUAL_ENTITY_1': {'MEMBER_RECORDS': [{'INTERNAL_ID': 1,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1017'}]}],
                                                            'VIRTUAL_ENTITY_ID': 'V1'},
                                       'VIRTUAL_ENTITY_2': {'MEMBER_RECORDS': [{'INTERNAL_ID': 35,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1016'}]},
                                                                               {'INTERNAL_ID': 44,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1015'}]}],
                                                            'VIRTUAL_ENTITY_ID': 'V35-S1'}},
                                      {'INBOUND_VIRTUAL_ENTITY_ID': 'V1-S2',
                                       'MATCH_INFO': {'ERRULE_CODE': 'CNAME_CFF_CEXCL',
                                                      'FEATURE_SCORES': {'DOB': [{'CANDIDATE_FEAT': '10/28/76',
                                                                                  'CANDIDATE_FEAT_ID': 100017,
                                                                                  'CANDIDATE_FEAT_USAGE_TYPE': '',
                                                                                  'FULL_SCORE': 93,
                                                                                  'INBOUND_FEAT': '10/27/76',
                                                                                  'INBOUND_FEAT_ID': 100087,
                                                                                  'INBOUND_FEAT_USAGE_TYPE': '',
                                                                                  'SCORE_BEHAVIOR': 'FMES',
                                                                                  'SCORE_BUCKET': 'CLOSE'}],
                                                                         'NAME': [{'CANDIDATE_FEAT': 'Marie '
                                                                                                     'Kusha',
                                                                                   'CANDIDATE_FEAT_ID': 100012,
                                                                                   'CANDIDATE_FEAT_USAGE_TYPE': 'PRIMARY',
                                                                                   'GENERATION_MATCH': -1,
                                                                                   'GNR_FN': 100,
                                                                                   'GNR_GN': 100,
                                                                                   'GNR_ON': -1,
                                                                                   'GNR_SN': 100,
                                                                                   'INBOUND_FEAT': 'Marie '
                                                                                                   'Kusha',
                                                                                   'INBOUND_FEAT_ID': 100012,
                                                                                   'INBOUND_FEAT_USAGE_TYPE': 'PRIMARY',
                                                                                   'SCORE_BEHAVIOR': 'NAME',
                                                                                   'SCORE_BUCKET': 'SAME'}],
                                                                         'PHONE': [{'CANDIDATE_FEAT': '512-353-8633',
                                                                                    'CANDIDATE_FEAT_ID': 100023,
                                                                                    'CANDIDATE_FEAT_USAGE_TYPE': 'HOME',
                                                                                    'FULL_SCORE': 100,
                                                                                    'INBOUND_FEAT': '512-353-8633',
                                                                                    'INBOUND_FEAT_ID': 100023,
                                                                                    'INBOUND_FEAT_USAGE_TYPE': 'HOME',
                                                                                    'SCORE_BEHAVIOR': 'FF',
                                                                                    'SCORE_BUCKET': 'SAME'}],
                                                                         'RECORD_TYPE': [{'CANDIDATE_FEAT': 'PERSON',
                                                                                          'CANDIDATE_FEAT_ID': 100020,
                                                                                          'CANDIDATE_FEAT_USAGE_TYPE': '',
                                                                                          'FULL_SCORE': 100,
                                                                                          'INBOUND_FEAT': 'PERSON',
                                                                                          'INBOUND_FEAT_ID': 100020,
                                                                                          'INBOUND_FEAT_USAGE_TYPE': '',
                                                                                          'SCORE_BEHAVIOR': 'FVME',
                                                                                          'SCORE_BUCKET': 'SAME'}]},
                                                      'MATCH_KEY': '+NAME+DOB+PHONE'},
                                       'RESULT_VIRTUAL_ENTITY_ID': 'V1-S3',
                                       'STEP': 3,
                                       'VIRTUAL_ENTITY_1': {'MEMBER_RECORDS': [{'INTERNAL_ID': 1,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1017'}]},
                                                                               {'INTERNAL_ID': 35,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1016'}]},
                                                                               {'INTERNAL_ID': 44,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1015'}]}],
                                                            'VIRTUAL_ENTITY_ID': 'V1-S2'},
                                       'VIRTUAL_ENTITY_2': {'MEMBER_RECORDS': [{'INTERNAL_ID': 4,
                                                                                'RECORDS': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                                             'RECORD_ID': '1018'}]}],
                                                            'VIRTUAL_ENTITY_ID': 'V4'}}]}}

#
# Search Attrs
#
# https://docs.senzing.com/python/3/g2engine/searching/index.html#searchbyattributes
SEARCH_NAME_FULL_BOB_SMITH = \
{'RESOLVED_ENTITIES': [{'ENTITY': {'RESOLVED_ENTITY': {'ENTITY_ID': 2,
                                                       'ENTITY_NAME': 'Robert '
                                                                      'Smith',
                                                       'FEATURES': {'ADDRESS': [{'FEAT_DESC': '1515 '
                                                                                              'Adela '
                                                                                              'Lane '
                                                                                              'Las '
                                                                                              'Vegas '
                                                                                              'NV '
                                                                                              '89111',
                                                                                 'FEAT_DESC_VALUES': [{'FEAT_DESC': '1515 '
                                                                                                                    'Adela '
                                                                                                                    'Lane '
                                                                                                                    'Las '
                                                                                                                    'Vegas '
                                                                                                                    'NV '
                                                                                                                    '89111',
                                                                                                       'LIB_FEAT_ID': 100107},
                                                                                                      {'FEAT_DESC': '1515 '
                                                                                                                    'Adela '
                                                                                                                    'Ln '
                                                                                                                    'Las '
                                                                                                                    'Vegas '
                                                                                                                    'NV '
                                                                                                                    '89132',
                                                                                                       'LIB_FEAT_ID': 100112}],
                                                                                 'LIB_FEAT_ID': 100107,
                                                                                 'USAGE_TYPE': 'HOME'},
                                                                                {'FEAT_DESC': '123 '
                                                                                              'Main '
                                                                                              'Street, '
                                                                                              'Las '
                                                                                              'Vegas '
                                                                                              'NV '
                                                                                              '89132',
                                                                                 'FEAT_DESC_VALUES': [{'FEAT_DESC': '123 '
                                                                                                                    'Main '
                                                                                                                    'Street, '
                                                                                                                    'Las '
                                                                                                                    'Vegas '
                                                                                                                    'NV '
                                                                                                                    '89132',
                                                                                                       'LIB_FEAT_ID': 100094}],
                                                                                 'LIB_FEAT_ID': 100094,
                                                                                 'USAGE_TYPE': 'MAILING'}],
                                                                    'DOB': [{'FEAT_DESC': '11/12/1979',
                                                                             'FEAT_DESC_VALUES': [{'FEAT_DESC': '11/12/1979',
                                                                                                   'LIB_FEAT_ID': 100101}],
                                                                             'LIB_FEAT_ID': 100101},
                                                                            {'FEAT_DESC': '12/11/1978',
                                                                             'FEAT_DESC_VALUES': [{'FEAT_DESC': '12/11/1978',
                                                                                                   'LIB_FEAT_ID': 100016},
                                                                                                  {'FEAT_DESC': '11/12/1978',
                                                                                                   'LIB_FEAT_ID': 100096}],
                                                                             'LIB_FEAT_ID': 100016}],
                                                                    'EMAIL': [{'FEAT_DESC': 'bsmith@work.com',
                                                                               'FEAT_DESC_VALUES': [{'FEAT_DESC': 'bsmith@work.com',
                                                                                                     'LIB_FEAT_ID': 100021}],
                                                                               'LIB_FEAT_ID': 100021}],
                                                                    'NAME': [{'FEAT_DESC': 'B '
                                                                                           'Smith',
                                                                              'FEAT_DESC_VALUES': [{'FEAT_DESC': 'B '
                                                                                                                 'Smith',
                                                                                                    'LIB_FEAT_ID': 100092}],
                                                                              'LIB_FEAT_ID': 100092,
                                                                              'USAGE_TYPE': 'PRIMARY'},
                                                                             {'FEAT_DESC': 'Robert '
                                                                                           'Smith',
                                                                              'FEAT_DESC_VALUES': [{'FEAT_DESC': 'Robert '
                                                                                                                 'Smith',
                                                                                                    'LIB_FEAT_ID': 100081},
                                                                                                   {'FEAT_DESC': 'Bob '
                                                                                                                 'J '
                                                                                                                 'Smith',
                                                                                                    'LIB_FEAT_ID': 100011},
                                                                                                   {'FEAT_DESC': 'Bob '
                                                                                                                 'Smith',
                                                                                                    'LIB_FEAT_ID': 100088}],
                                                                              'LIB_FEAT_ID': 100081,
                                                                              'USAGE_TYPE': 'PRIMARY'}],
                                                                    'PHONE': [{'FEAT_DESC': '702-919-1300',
                                                                               'FEAT_DESC_VALUES': [{'FEAT_DESC': '702-919-1300',
                                                                                                     'LIB_FEAT_ID': 100115}],
                                                                               'LIB_FEAT_ID': 100115,
                                                                               'USAGE_TYPE': 'HOME'},
                                                                              {'FEAT_DESC': '702-919-1300',
                                                                               'FEAT_DESC_VALUES': [{'FEAT_DESC': '702-919-1300',
                                                                                                     'LIB_FEAT_ID': 100115}],
                                                                               'LIB_FEAT_ID': 100115,
                                                                               'USAGE_TYPE': 'MOBILE'}],
                                                                    'RECORD_TYPE': [{'FEAT_DESC': 'PERSON',
                                                                                     'FEAT_DESC_VALUES': [{'FEAT_DESC': 'PERSON',
                                                                                                           'LIB_FEAT_ID': 100020}],
                                                                                     'LIB_FEAT_ID': 100020}]},
                                                       'LAST_SEEN_DT': '2023-05-28 '
                                                                       '19:06:24.639',
                                                       'RECORD_SUMMARY': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                           'FIRST_SEEN_DT': '2023-05-28 '
                                                                                            '19:06:19.786',
                                                                           'LAST_SEEN_DT': '2023-05-28 '
                                                                                           '19:06:24.639',
                                                                           'RECORD_COUNT': 4}]}},
                        'MATCH_INFO': {'ERRULE_CODE': 'CNAME',
                                       'FEATURE_SCORES': {'NAME': [{'CANDIDATE_FEAT': 'Robert '
                                                                                      'Smith',
                                                                    'GENERATION_MATCH': -1,
                                                                    'GNR_FN': 97,
                                                                    'GNR_GN': -1,
                                                                    'GNR_ON': -1,
                                                                    'GNR_SN': -1,
                                                                    'INBOUND_FEAT': 'Bob '
                                                                                    'Smith'},
                                                                   {'CANDIDATE_FEAT': 'Bob '
                                                                                      'J '
                                                                                      'Smith',
                                                                    'GENERATION_MATCH': -1,
                                                                    'GNR_FN': 93,
                                                                    'GNR_GN': -1,
                                                                    'GNR_ON': -1,
                                                                    'GNR_SN': -1,
                                                                    'INBOUND_FEAT': 'Bob '
                                                                                    'Smith'}]},
                                       'MATCH_KEY': '+NAME',
                                       'MATCH_LEVEL': 2,
                                       'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}},
                       {'ENTITY': {'RESOLVED_ENTITY': {'ENTITY_ID': 38,
                                                       'ENTITY_NAME': 'Robert '
                                                                      'E Smith '
                                                                      'Sr',
                                                       'FEATURES': {'ADDRESS': [{'FEAT_DESC': '123 '
                                                                                              'E '
                                                                                              'Main '
                                                                                              'St '
                                                                                              'Henderson '
                                                                                              'NV '
                                                                                              '89132',
                                                                                 'FEAT_DESC_VALUES': [{'FEAT_DESC': '123 '
                                                                                                                    'E '
                                                                                                                    'Main '
                                                                                                                    'St '
                                                                                                                    'Henderson '
                                                                                                                    'NV '
                                                                                                                    '89132',
                                                                                                       'LIB_FEAT_ID': 100114}],
                                                                                 'LIB_FEAT_ID': 100114,
                                                                                 'USAGE_TYPE': 'MAILING'},
                                                                                {'FEAT_DESC': '123 '
                                                                                              'Main '
                                                                                              'St, '
                                                                                              'Las '
                                                                                              'Vegas',
                                                                                 'FEAT_DESC_VALUES': [{'FEAT_DESC': '123 '
                                                                                                                    'Main '
                                                                                                                    'St, '
                                                                                                                    'Las '
                                                                                                                    'Vegas',
                                                                                                       'LIB_FEAT_ID': 300056}],
                                                                                 'LIB_FEAT_ID': 300056,
                                                                                 'USAGE_TYPE': 'MAILING'}],
                                                                    'DOB': [{'FEAT_DESC': '3/31/1954',
                                                                             'FEAT_DESC_VALUES': [{'FEAT_DESC': '3/31/1954',
                                                                                                   'LIB_FEAT_ID': 300051}],
                                                                             'LIB_FEAT_ID': 300051}],
                                                                    'DRLIC': [{'FEAT_DESC': '112233 '
                                                                                            'NV',
                                                                               'FEAT_DESC_VALUES': [{'FEAT_DESC': '112233 '
                                                                                                                  'NV',
                                                                                                     'LIB_FEAT_ID': 100127}],
                                                                               'LIB_FEAT_ID': 100127}],
                                                                    'NAME': [{'FEAT_DESC': 'Robert '
                                                                                           'E '
                                                                                           'Smith '
                                                                                           'Sr',
                                                                              'FEAT_DESC_VALUES': [{'FEAT_DESC': 'Robert '
                                                                                                                 'E '
                                                                                                                 'Smith '
                                                                                                                 'Sr',
                                                                                                    'LIB_FEAT_ID': 300047},
                                                                                                   {'FEAT_DESC': 'Robbie '
                                                                                                                 'Smith',
                                                                                                    'LIB_FEAT_ID': 100097}],
                                                                              'LIB_FEAT_ID': 300047,
                                                                              'USAGE_TYPE': 'PRIMARY'}],
                                                                    'RECORD_TYPE': [{'FEAT_DESC': 'PERSON',
                                                                                     'FEAT_DESC_VALUES': [{'FEAT_DESC': 'PERSON',
                                                                                                           'LIB_FEAT_ID': 100020}],
                                                                                     'LIB_FEAT_ID': 100020}]},
                                                       'LAST_SEEN_DT': '2023-05-28 '
                                                                       '19:07:51.446',
                                                       'RECORD_SUMMARY': [{'DATA_SOURCE': 'CUSTOMERS',
                                                                           'FIRST_SEEN_DT': '2023-05-28 '
                                                                                            '19:06:19.788',
                                                                           'LAST_SEEN_DT': '2023-05-28 '
                                                                                           '19:06:19.788',
                                                                           'RECORD_COUNT': 1},
                                                                          {'DATA_SOURCE': 'WATCHLIST',
                                                                           'FIRST_SEEN_DT': '2023-05-28 '
                                                                                            '19:07:51.446',
                                                                           'LAST_SEEN_DT': '2023-05-28 '
                                                                                           '19:07:51.446',
                                                                           'RECORD_COUNT': 1}]}},
                        'MATCH_INFO': {'ERRULE_CODE': 'CNAME',
                                       'FEATURE_SCORES': {'NAME': [{'CANDIDATE_FEAT': 'Robert '
                                                                                      'E '
                                                                                      'Smith '
                                                                                      'Sr',
                                                                    'GENERATION_MATCH': -1,
                                                                    'GNR_FN': 90,
                                                                    'GNR_GN': -1,
                                                                    'GNR_ON': -1,
                                                                    'GNR_SN': -1,
                                                                    'INBOUND_FEAT': 'Bob '
                                                                                    'Smith'},
                                                                   {'CANDIDATE_FEAT': 'Robbie '
                                                                                      'Smith',
                                                                    'GENERATION_MATCH': -1,
                                                                    'GNR_FN': 97,
                                                                    'GNR_GN': -1,
                                                                    'GNR_ON': -1,
                                                                    'GNR_SN': -1,
                                                                    'INBOUND_FEAT': 'Bob '
                                                                                    'Smith'}]},
                                       'MATCH_KEY': '+NAME',
                                       'MATCH_LEVEL': 2,
                                       'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}},
                       {'ENTITY': {'RESOLVED_ENTITY': {'ENTITY_ID': 200001,
                                                       'ENTITY_NAME': 'Robert '
                                                                      'Smith',
                                                       'FEATURES': {'EMAIL': [{'FEAT_DESC': 'robert.smith@email.com',
                                                                               'FEAT_DESC_VALUES': [{'FEAT_DESC': 'robert.smith@email.com',
                                                                                                     'LIB_FEAT_ID': 300001}],
                                                                               'LIB_FEAT_ID': 300001}],
                                                                    'NAME': [{'FEAT_DESC': 'Robert '
                                                                                           'Smith',
                                                                              'FEAT_DESC_VALUES': [{'FEAT_DESC': 'Robert '
                                                                                                                 'Smith',
                                                                                                    'LIB_FEAT_ID': 100081}],
                                                                              'LIB_FEAT_ID': 100081,
                                                                              'USAGE_TYPE': 'PRIMARY'}],
                                                                    'RECORD_TYPE': [{'FEAT_DESC': 'PERSON',
                                                                                     'FEAT_DESC_VALUES': [{'FEAT_DESC': 'PERSON',
                                                                                                           'LIB_FEAT_ID': 100020}],
                                                                                     'LIB_FEAT_ID': 100020}]},
                                                       'LAST_SEEN_DT': '2023-05-28 '
                                                                       '19:07:51.448',
                                                       'RECORD_SUMMARY': [{'DATA_SOURCE': 'WATCHLIST',
                                                                           'FIRST_SEEN_DT': '2023-05-28 '
                                                                                            '19:07:51.448',
                                                                           'LAST_SEEN_DT': '2023-05-28 '
                                                                                           '19:07:51.448',
                                                                           'RECORD_COUNT': 1}]}},
                        'MATCH_INFO': {'ERRULE_CODE': 'CNAME',
                                       'FEATURE_SCORES': {'NAME': [{'CANDIDATE_FEAT': 'Robert '
                                                                                      'Smith',
                                                                    'GENERATION_MATCH': -1,
                                                                    'GNR_FN': 97,
                                                                    'GNR_GN': -1,
                                                                    'GNR_ON': -1,
                                                                    'GNR_SN': -1,
                                                                    'INBOUND_FEAT': 'Bob '
                                                                                    'Smith'}]},
                                       'MATCH_KEY': '+NAME',
                                       'MATCH_LEVEL': 2,
                                       'MATCH_LEVEL_CODE': 'POSSIBLY_SAME'}}]}

